runtime: python39
entrypoint: gunicorn -b :$PORT flaskr.init:app
basic_scaling:
 max_instances: 1
 idle_timeout: 30m
env_variables:
 FLASK_APP: flaskr
 FLASK_ENV: production
 AWS_ACCESS_KEY_ID: ASIAYOER6CFKMZIOLX6L
 AWS_SECRET_ACCESS_KEY: i9Q1SyLf1AfCLd8BFhZ/qo8J9I4uFh8EOTqpICot
 AWS_SESSION_TOKEN: FwoGZXIvYXdzEPX//////////wEaDIZbplUb7B7m+YhoRiLFAeDMlQ1iyH/YDYPPDLqQkyDBjseya11h0sfmGfPZ05lV+GJwoVUtFA+DUUi/7CoAUL5nmAlSCFzz3Sp4GbiICPwyyKNfRmV0kfk+fM6bonK+Ybn8BeigwljrIZMSw2wubZ4ck85A5d2qw/5BxQZaZcvYDaKhJdt2S7gTtvzaFfZeoz+0zYJCsfE/eac7F5sJZjPGwGh1V1IHV2iV0QC00NPUVmJrnh7mJvDCx5DyjmA5GHLlBABb5aBGY37wfFaaaA6/kTuqKJaEjpQGMi1BCaq67Kyu0CM7WACn4qasDfzUyuxIi537Oenci46X62OP/K1LoTHYRvZzRxo=
 AWS_DEFAULT_REGION: us-east-1
